# Generated by Django 2.1.5 on 2019-05-08 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_item_review'),
        ('shop', '0005_auto_20190421_1701'),
        ('shop', '0004_item_review'),
    ]

    operations = [
    ]
