# Generated by Django 2.1.5 on 2019-05-08 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_merge_20190508_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='review',
        ),
        migrations.AlterField(
            model_name='item',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='photo',
            field=models.ImageField(upload_to=''),
        ),
    ]
